name: Studio Lite / Build Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps.json"
      - "images/**"

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Studio Lite
        uses: docker/build-push-action@v7
        with:
          context: .
          file: images/custom/Containerfile
          platforms: linux/amd64
          push: true
          pull: true

          tags: |
            ghcr.io/ramananbuilds/studio-lite:latest
            ghcr.io/ramananbuilds/studio-lite:v16
            ghcr.io/ramananbuilds/studio-lite:${{ github.sha }}

          build-args: |
            FRAPPE_PATH=https://github.com/ramananbuilds/frappe
            FRAPPE_BRANCH=studiolite-v16
            CACHE_BUST=${{ github.run_id }}

          secret-files: |
            apps_json=apps.json

          cache-from: type=gha,scope=studio-lite-v16
          cache-to: type=gha,mode=max,scope=studio-lite-v16
